"""Initial db

Revision ID: 0f25e0fd5152
Revises: 
Create Date: 2023-03-06 21:15:32.199192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f25e0fd5152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    question_table = op.create_table('Question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('vk_id')
    )
    answers_table = op.create_table('Answer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoadMap',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Statistic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=False),
    sa.Column('failures', sa.BigInteger(), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GameAnswer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['Answer.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # op.bulk_insert(
    #     question_table,
    #     [
    #         {
    #             'id': 1,
    #             "title": "Что может неожиданно повыситься?"
    #         },
    #         {
    #             'id': 2,
    #             "title": "Кто из отечественных артистов мог или может собрать целый зал зрителей, аккомпанируя себе на акустической гитаре?"
    #         },
    #     ])
    op.bulk_insert(
    question_table,
    [
        {
            'id': 1,
            "title": "Разведение каких насекомых может стать бизнесом?"
        },
        {
            'id': 2,
            "title": "Зачем молодожёны по пути в ЗАГС остановили свой кортеж на 10 минут?"
        },
        {
            'id': 3,
            "title": "Как можно одним словом ответить на вопрос - Зачем ты женился?"
        },
        {
            'id': 4,
            "title": "Какой напиток хозяйка деревенского дома обычно делает сама?"
        },
        {
            'id': 5,
            "title": "Какое природное явление меняет привычное освещение местности?"
        },
        {
            'id': 6,
            "title": "Зачем посетитель ресторана попросил позвать шеф-повара?"
        },
        {
            'id': 7,
            "title": "Что юноша мог принести на первое свидание, решив что цветы это банально? "
        },
        {
            'id': 8,
            "title": "Какие живые существа строят общее жилье для большого количества особей?"
        },
        {
            'id': 9,
            "title": "Кем можно работать в парке? (творительный падеж)"
        },
        {
            'id': 10,
            "title": "Что кроме хлеба или мяса может входить в бургер или сэндвич? (единственное число)"
        },
        {
            'id': 11,
            "title": "Не удивляйся сейчас так модно, успокоила дочь маму. Чему удивилась мама?"
        },
        {
            'id': 12,
            "title": "Назовите самого известного советского или российского физика?"
        },
    ])
    op.bulk_insert(
        answers_table,
        [
            {
                'id': 1,
                "title": "Пчелы",
                "score": 29,
                "question_id": 1,
            },
            {
                'id': 2,
                "title": "Бабочки",
                "score": 17,
                "question_id": 1,
            },
            {
                'id': 3,
                "title": "Шелкопряд",
                "score": 12,
                "question_id": 1,
            },
            {
                'id': 4,
                "title": "Тараканы",
                "score": 10,
                "question_id": 1,
            },
            {
                'id': 5,
                "title": "Пиявки",
                "score": 7,
                "question_id": 1,
            },
            {
                'id': 6,
                "title": "Мотыль",
                "score": 6,
                "question_id": 1,
            },
            {
                'id': 7,
                "title": "Сфотографироваться",
                "score": 38,
                "question_id": 2,
            },
            {
                'id': 8,
                "title": "Возложить цветы",
                "score": 11,
                "question_id": 2,
            },
            {
                'id': 9,
                "title": "На заправку",
                "score": 10,
                "question_id": 2,
            },
            {
                'id': 10,
                "title": "В туалет",
                "score": 7,
                "question_id": 2,
            },
            {
                'id': 11,
                "title": "Выпить",
                "score": 6,
                "question_id": 2,
            },
            {
                'id': 12,
                "title": "Ждут отстающих",
                "score": 4,
                "question_id": 2,
            },
            {
                'id': 13,
                "title": "Полюбил",
                "score": 40,
                "question_id": 3,
            },
            {
                'id': 14,
                "title": "Пора",
                "score": 15,
                "question_id": 3,
            },
            {
                'id': 15,
                "title": "Беременность",
                "score": 9,
                "question_id": 3,
            },
            {
                'id': 16,
                "title": "Заставили",
                "score": 8,
                "question_id": 3,
            },
            {
                'id': 17,
                "title": "Обещал",
                "score": 6,
                "question_id": 3,
            },
            {
                'id': 18,
                "title": "Дурак",
                "score": 5,
                "question_id": 3,
            },
            {
                'id': 19,
                "title": "Компот",
                "score": 40,
                "question_id": 4,
            },
            {
                'id': 20,
                "title": "Квас",
                "score": 15,
                "question_id": 4,
            },
            {
                'id': 21,
                "title": "Морс",
                "score": 9,
                "question_id": 4,
            },
            {
                'id': 22,
                "title": "Самогон",
                "score": 8,
                "question_id": 4,
            },
            {
                'id': 23,
                "title": "Чай",
                "score": 6,
                "question_id": 4,
            },
            {
                'id': 24,
                "title": "Простокваша",
                "score": 5,
                "question_id": 4,
            },
            {
                'id': 25,
                "title": "Молния",
                "score": 37,
                "question_id": 5,
            },
            {
                'id': 26,
                "title": "Затмение",
                "score": 13,
                "question_id": 5,
            },
            {
                'id': 27,
                "title": "Северное сияние",
                "score": 11,
                "question_id": 5,
            },
            {
                'id': 28,
                "title": "Туман",
                "score": 10,
                "question_id": 5,
            },
            {
                'id': 29,
                "title": "Извержение вулкана",
                "score": 6,
                "question_id": 5,
            },
            {
                'id': 30,
                "title": "Белые ночи",
                "score": 5,
                "question_id": 5,
            },
            {
                'id': 31,
                "title": "Поблагодарить",
                "score": 50,
                "question_id": 6,
            },
            {
                'id': 32,
                "title": "Пожаловаться",
                "score": 23,
                "question_id": 6,
            },
            {
                'id': 33,
                "title": "Узнать рецепт",
                "score": 13,
                "question_id": 6,
            },
            {
                'id': 34,
                "title": "Познакомиться",
                "score": 6,
                "question_id": 6,
            },
            {
                'id': 35,
                "title": "Сделать спецзаказ",
                "score": 5,
                "question_id": 6,
            },
            {
                'id': 36,
                "title": "Вручить приз",
                "score": 3,
                "question_id": 6,
            },
            {
                'id': 37,
                "title": "Сладости",
                "score": 39,
                "question_id": 7,
            },
            {
                'id': 38,
                "title": "Билеты в театр",
                "score": 12,
                "question_id": 7,
            },
            {
                'id': 39,
                "title": "Игрушка",
                "score": 10,
                "question_id": 7,
            },
            {
                'id': 40,
                "title": "Вино",
                "score": 6,
                "question_id": 7,
            },
            {
                'id': 41,
                "title": "Сувенир",
                "score": 5,
                "question_id": 7,
            },
            {
                'id': 42,
                "title": "Стихи",
                "score": 4,
                "question_id": 7,
            },
            {
                'id': 43,
                "title": "Муравьи",
                "score": 39,
                "question_id": 8,
            },
            {
                'id': 44,
                "title": "Пчелы",
                "score": 12,
                "question_id": 8,
            },
            {
                'id': 45,
                "title": "Бобры",
                "score": 10,
                "question_id": 8,
            },
            {
                'id': 46,
                "title": "Люди",
                "score": 6,
                "question_id": 8,
            },
            {
                'id': 47,
                "title": "Термиты",
                "score": 5,
                "question_id": 8,
            },
            {
                'id': 48,
                "title": "Осы",
                "score": 4,
                "question_id": 8,
            },
           {
                'id': 49,
                "title": "Садовником",
                "score": 26,
                "question_id": 9,
            },
            {
                'id': 50,
                "title": "Дворником",
                "score": 24,
                "question_id": 9,
            },
            {
                'id': 51,
                "title": "Сторожем",
                "score": 20,
                "question_id": 9,
            },
            {
                'id': 52,
                "title": "Кассиром",
                "score": 8,
                "question_id": 9,
            },
            {
                'id': 53,
                "title": "Продавцом",
                "score": 7,
                "question_id": 9,
            },
            {
                'id': 54,
                "title": "Оператором аттракционов",
                "score": 5,
                "question_id": 9,
            },
           {
                'id': 55,
                "title": "Сыр",
                "score": 27,
                "question_id": 10,
            },
            {
                'id': 56,
                "title": "Салат",
                "score": 18,
                "question_id": 10,
            },
            {
                'id': 57,
                "title": "Помидор",
                "score": 13,
                "question_id": 10,
            },
            {
                'id': 58,
                "title": "Соус",
                "score": 10,
                "question_id": 10,
            },
            {
                'id': 59,
                "title": "Соленый огурец",
                "score": 9,
                "question_id": 10,
            },
            {
                'id': 60,
                "title": "Яйцо",
                "score": 6,
                "question_id": 10,
            },
            {
                'id': 61,
                "title": "Рваные джинсы",
                "score": 22,
                "question_id": 11,
            },
           {
                'id': 62,
                "title": "Странная обувь",
                "score": 13,
                "question_id": 11,
            },
            {
                'id': 63,
                "title": "Меховые тапки",
                "score": 9,
                "question_id": 11,
            },
            {
                'id': 64,
                "title": "Разноцветные волосы",
                "score": 8,
                "question_id": 11,
            },
            {
                'id': 65,
                "title": "Растянутые вещи",
                "score": 7,
                "question_id": 11,
            },
            {
                'id': 66,
                "title": "Татуировки",
                "score": 5,
                "question_id": 11,
            },
            {
                'id': 67,
                "title": "Курчатов",
                "score": 22,
                "question_id": 12,
            },
           {
                'id': 68,
                "title": "Ландау",
                "score": 13,
                "question_id": 12,
            },
            {
                'id': 69,
                "title": "Капица",
                "score": 10,
                "question_id": 12,
            },
            {
                'id': 70,
                "title": "Сахаров",
                "score": 9,
                "question_id": 12,
            },
            {
                'id': 71,
                "title": "Алфёров",
                "score": 5,
                "question_id": 12,
            },
            {
                'id': 72,
                "title": "Келдыш",
                "score": 3,
                "question_id": 12,
            },
        ])
    # op.bulk_insert(
    #     answers_table,
    #     [
    #         {
    #             'id': 1,
    #             "title": "Температура",
    #             "score": 32,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 2,
    #             "title": "Давление",
    #             "score": 25,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 3,
    #             "title": "Курс доллара",
    #             "score": 19,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 4,
    #             "title": "Зарплата",
    #             "score": 8,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 5,
    #             "title": "Цены",
    #             "score": 6,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 6,
    #             "title": "Настроение",
    #             "score": 5,
    #             "question_id": 1,
    #         },
    #         {
    #             'id': 7,
    #             "title": "Высоцкий",
    #             "question_id": 2,
    #             "score": 29
    #         },
    #         {
    #             'id': 8,
    #             "title": "Окуджава",
    #             "score": 20,
    #             "question_id": 2,
    #         },
    #         {
    #             'id': 9,
    #             "title": "Розенбаум",
    #             "score": 15,
    #             "question_id": 2,
    #         },
    #         {
    #             'id': 10,
    #             "title": "Цой",
    #             "score": 7,
    #             "question_id": 2,
    #         },
    #         {
    #             'id': 11,
    #             "title": "Антонов",
    #             "score": 5,
    #             "question_id": 2,
    #         },
    #         {
    #             'id': 12,
    #             "title": "Макаревич",
    #             "score": 4,
    #             "question_id": 2,
    #         },

    #     ])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GameAnswer')
    op.drop_table('Statistic')
    op.drop_table('RoadMap')
    op.drop_table('Answer')
    op.drop_table('admins')
    op.drop_table('User')
    op.drop_table('Question')
    op.drop_table('Game')
    # ### end Alembic commands ###
