"""Rename gametable column

Revision ID: 354defd5a5e0
Revises: a2594c560ce6
Create Date: 2023-03-01 22:31:51.421721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '354defd5a5e0'
down_revision = 'a2594c560ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Game', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.drop_column('Game', 'ended_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Game', sa.Column('ended_ad', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Game', 'ended_at')
    # ### end Alembic commands ###
