"""Remove factor from question

Revision ID: 4aa8d7fce8ca
Revises: 354defd5a5e0
Create Date: 2023-03-02 00:51:33.822722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa8d7fce8ca'
down_revision = '354defd5a5e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('factor', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
