"""Change game table add nullable end time

Revision ID: a2594c560ce6
Revises: 339b2bd84ccc
Create Date: 2023-03-01 22:25:37.713720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2594c560ce6'
down_revision = '339b2bd84ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
