name: Publish Dockerhub
on:
  push:
    branches: ['deployment']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: $tr0ngPa$$w0rd
          POSTGRES_USER: test_user
          POSTGRES_DB: amigos_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
#      - name: Checkout code
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: handle migrations
        run:  alembic upgrade head
      - name: Test with pytest
        run: |
          pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          repository:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amigos:latest
